{
  "name": "DOCS",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    }
  },
  "jobs": {
    "build-docs": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v1"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v1",
          "with": {
            "asdf-system": "docs-builder"
          }
        },
        {
        "name": "Start SSH session",
        "uses": "luchihoratiu/debug-via-ssh@main",
        "with": {
          "NGROK_AUTH_TOKEN": "${{ secrets.NGROK_AUTH_TOKEN }}",
          "NGROK_REGION": "eu",
          "SSH_PASS": "${{ secrets.SSH_PASS }}"
          }
        },
        {
          "name": "Build Docs",
          "uses": "40ants/build-docs@v1",
          "with": {
            "asdf-system": "docs-builder",
            "error-on-warnings": false
          }
        }
      ]
    }
  }
}
